import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/provider/auth.provider";
import { Toaster } from "@/components/ui/toaster";
import { CartProvider } from "@/provider/cart.provider";
import { useEffect } from "react";
import { ChatProvider } from "@/provider/chat.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />

        <AuthProvider>
          <CartProvider>
            <ChatProvider>{children}</ChatProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
